// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartLedger.Services;

#nullable disable

namespace SmartLedger.Migrations
{
    [DbContext(typeof(SmartLedgerDbContext))]
    [Migration("20260816120917_AddBuchungenTabelle")]
    partial class AddBuchungenTabelle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("SmartLedger.Models.Beitragszahlung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jahr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kommentar")
                        .HasColumnType("TEXT");

                    b.Property<int>("MitgliedId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Monat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MitgliedId");

                    b.ToTable("Beitragszahlungen");
                });

            modelBuilder.Entity("SmartLedger.Models.Buchung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Betrag")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BuchungsDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Verwendungszweck")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Buchungen");
                });

            modelBuilder.Entity("SmartLedger.Models.Mitglied", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuchungId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Haushaltsgruppe")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monatsbeitrag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuchungId");

                    b.ToTable("Mitglieder");
                });

            modelBuilder.Entity("SmartLedger.Models.Beitragszahlung", b =>
                {
                    b.HasOne("SmartLedger.Models.Mitglied", "Mitglied")
                        .WithMany()
                        .HasForeignKey("MitgliedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mitglied");
                });

            modelBuilder.Entity("SmartLedger.Models.Mitglied", b =>
                {
                    b.HasOne("SmartLedger.Models.Buchung", null)
                        .WithMany("ZugeordneteMitglieder")
                        .HasForeignKey("BuchungId");
                });

            modelBuilder.Entity("SmartLedger.Models.Buchung", b =>
                {
                    b.Navigation("ZugeordneteMitglieder");
                });
#pragma warning restore 612, 618
        }
    }
}
